# Site settings
title: Alces Flight
email: github@alces-flight.com
description: >
  Alces Flight Open Source Products
baseurl: ""
url: "http://alces-flight.github.io/"
twitter_username: alces-flight
github_username: alces-flight

# Build settings
markdown: kramdown
